version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
      - DATABASE_URL=postgres://latte:latte@db:5432/frappuccino?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U latte -d frappuccino"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
